version: "3"

services:
  nodejs-app:
    build: .
    ports:
      - "3000:3000" # Expose Node.js app on port 3000

  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080" # Expose NGINX on port 8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nodejs-app
