# Use the official NGinx image from the Docker Hub
FROM nginx:latest

# Copy the contents of the public folder to NGinx's default HTML directory
COPY public /usr/share/nginx/html

# Expose port 80 to the host
EXPOSE 80
